---

- name: apt update
  apt:
    update_cache: yes
  become: yes

- name: apt upgrade
  apt:
    upgrade: safe
  become: yes

- name: install bluetooth firmware
  apt:
    name: pi-bluetooth
  become: yes
  register: bluetooth_installed

- name: reboot
  reboot:
  when: bluetooth_installed.changed

- name: add mosquitto repo key
  apt_key:
    url: https://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
    state: present
  become: yes

- name: add mosquitto sources
  apt_repository:
    repo: deb https://repo.mosquitto.org/debian stretch main
  become: yes

- name: install mosquitto
  apt:
    name:
      - libmosquitto-dev
      - mosquitto
      - mosquitto-clients
      - libmosquitto1
    update_cache: yes
  become: yes
