sensor.aeon_labs_zw100_multisensor_6_luminance:
  ignored: false
  polling_intensity: 2
sensor.aeon_labs_zw100_multisensor_6_temperature:
  ignored: false
  polling_intensity: 2
sensor.aeon_labs_zw100_multisensor_6_relative_humidity:
  ignored: false
  polling_intensity: 2
sensor.aeon_labs_zw100_multisensor_6_ultraviolet:
  ignored: false
  polling_intensity: 2
sensor.aeon_labs_zw100_multisensor_6_battery_level:
  ignored: false
  polling_intensity: 1
sensor.aeon_labs_zw100_multisensor_6_burglar_2:
  ignored: false
  polling_intensity: 2
sensor.aeon_labs_zw100_multisensor_6_burglar_3:
  ignored: false
  polling_intensity: 2
